format_version: 3
pipelines:
  kprpc:
    group: frontendLibs
    materials:
      mygit:
        type: configrepo
      placeholdersDependency:
        pipeline: placeholders
        stage: publish
    stages:
      - installDeps:
          #clean_workspace: true
          jobs:
            defaultJob:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - "ci"
      - build:
          jobs:
            defaultJob:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - "start"
      - test:
          jobs:
            defaultJob:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - "test"
      - publish:
          jobs:
            defaultJob:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - "publish"
                      - "dist"
