format_version: 3
pipelines:
  kprpc:
    group: frontendLibs
    environment_variables:
      SKIP_PUBLISH_TO_NPM: ""
    materials:
      mygit:
        type: configrepo
      placeholdersDependency:
        pipeline: placeholders
        stage: installBuildTestAndPublish
    stages:
      - installBuildTestAndPublish:
          tasks:
            - exec:
                command: npm
                arguments:
                  - "ci"
            - exec:
                command: npm
                arguments:
                  - "start"
            - exec:
                command: npm
                arguments:
                  - "test"
            - exec:
                command: /bin/bash
                arguments:
                  - "publish.sh"
